#!/bin/bash

build() {
    local firmware

    for firmware in rt24_os0_rcpu.elf rt24_os1_rcpu.elf; do
        add_file "/usr/lib/esos/${firmware}" "/lib/firmware/${firmware}"
    done
}

help() {
    cat <<HELPEOF
This hook includes SpacemiT ESOS firmware files in the initramfs.
HELPEOF
}
