#!/bin/bash
set -e

output=
previous=
for argument in "$@"; do
  if [[ $previous == -o ]]; then
    output=$argument
    break
  fi
  previous=$argument
done

if [[ -z $output ]]; then
  exec x86_64-linux-gnu-gcc "$@"
fi

x86_64-linux-gnu-gcc "$@"
mv "$output" "$output.x86_64"

cat > "$output" <<EOF
#!/bin/sh
exec /usr/bin/qemu-x86_64-static /usr/x86_64-linux-gnu/lib/ld-linux-x86-64.so.2 \\
  --library-path "$CRYSTAL_X86_LIBRARY_PATH" \\
  "\$0.x86_64" "\$@"
EOF
chmod +x "$output"
