on:
  workflow_dispatch: { }
  schedule:
    - cron: '0 0 * * *'

jobs:
  rotten:
    name: Check for rotten patches
    runs-on: ubuntu-latest
    container: archlinux/archlinux:latest
    steps:
      - name: Install dependencies
        run: pacman -Syu --noconfirm asp patch python python-sh python-gitpython python-pygithub pyalpm
      - name: Fix git unsafe repository
        run: git config --global --add safe.directory /__w/archriscv-packages/archriscv-packages
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v1
      - name: Check for rotten patches
        run: python find-rotten
        env:
          GITHUB_TOKEN: ${{ secrets.DILIGENT_BOT_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
